version: '1.0'
name: pipeline-20220121
displayName: pipeline-20220121
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-aee2a89d
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        commands:
          - sudo npm install node-gyp
          - npm i
          - 'rm -rf ./dist '
          - npm run build
strategy:
  stepTimeout: 5
permissions:
  - role: admin
    members: []
