version: '1.0'
name: pipeline-20220419
displayName: pipeline-20220419
triggers:
  trigger: manual
stages:
  - name: stage-b174d97a
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
permissions:
  - role: admin
    members: []
