version: '1.0'
name: pipeline-20220121
displayName: pipeline-20220121
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-129d7c64
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 12.16.1
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        commands:
          - npm install && rm -rf ./dist && npm run build
permissions:
  - role: admin
    members: []
